name: Bug Report
description: "Found a bug? Please search through existing issues to check if it has already been reported."
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: "Confirmation"
      options:
        - label: "I have searched existing bug reports and confirmed there are no duplicates"
          required: true
        - label: "I will provide as much detail as possible"
          required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Bug Description"
      description: "Please describe the bug concisely."
      placeholder: "What issue are you experiencing?"
    validations:
      required: true
  - type: textarea
    id: "to-reproduce"
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the bug"
      placeholder: "1. Go to '...' 2. Click on '...' 3. Scroll down to '...' 4. See error '...'"
    validations:
      required: true
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating System (OS)"
      multiple: false
      options:
        - "Select an OS"
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: input
    id: "os-version"
    attributes:
      label: "OS Version"
      description: "Example: macOS 14.0, Windows 11"
    validations:
      required: true
  - type: input
    id: "raql-version"
    attributes:
      label: "Raql Version"
      description: "Which version of Raql are you using?"
    validations:
      required: false
  - type: textarea
    id: "additional-context"
    attributes:
      label: "Additional Information"
      description: "Please add screenshots or any other information that might help."
    validations:
      required: false

