name: Feature Request
description: "Have an idea for a new feature? Please search through existing requests to see if it has already been suggested."
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: "Confirmation"
      options:
        - label: "I have searched existing feature requests and confirmed there are no duplicates"
          required: true
  - type: textarea
    id: "describe-solution"
    attributes:
      label: "Proposed Feature"
      description: "Please describe the feature or solution you'd like to see."
    validations:
      required: true
  - type: textarea
    id: "related-to-problem"
    attributes:
      label: "Problem to Solve"
      description: "Is this feature request related to a specific problem?"
      placeholder: "I find it difficult when..."
    validations:
      required: false
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating System (OS)"
      multiple: false
      options:
        - "Select an OS"
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: "importance"
    attributes:
      label: "How important is this feature to you?"
      multiple: false
      options:
        - "1 (Not very important)"
        - "2"
        - "3"
        - "4"
        - "5 (Very important!)"
    validations:
      required: true
